[package]
name = "dump-update-spike"
version = "0.0.1"
authors = ["Count Count <countvoncount123456@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.7", features = ["rt", "macros", "time", "signal"] }
thiserror = "1.0.26"
mediawiki = "0.2.3"
